import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Grid from '@mui/material/Grid'
import TextField from '@mui/material/TextField'
import Select from '@mui/material/Select'
import Paper from '@mui/material/Paper'
import { makeStyles } from '@mui/styles'

export default function Home() {
  const useStyles = makeStyles(() => ({
    root: { height: '500px', width: '1000px' },
    paper: { height: '100%', width: '100%' },
    container1: { height: '100%', background: 'blue' },
    container2: { height: '100%', width: '50%', background: 'orange' },
    container2: { height: '100%', width: '50%', background: 'purple' },
  }))

  const classes = useStyles()
  return (
    <div className={styles.container}>
      <Head>
        <title>Technical Test VereNFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid
        className={classes.root}
        justifyContent="center"
        alignItems="center">
        <Paper className={classes.paper}>
          <Grid container className={classes.container1}>
            <Grid className={classes.container2}></Grid>
            <Grid className={classes.container3}></Grid>
          </Grid>
        </Paper>
      </Grid>
    </div>
  )
}
